In [1]:
!pip install pympler

from pympler import asizeof
import numpy as np
from IPython.display import YouTubeVideo

# **Arrays**
**An array object represents a multidimensional, homogeneous array of fixed-size items.**

**The most common NumPy array is the "ndarray" or "N-dimensional array". An N-dimensional array is an array with any number of dimensions. The dimensions can vary from one-dimensional arrays to two-dimensional arrays, twenty one-dimensional arrays and beyond.**

**Elements within a NumPy array need to all be of the same data type. This contrasts with Python lists that can contain multiple data types within a list. Because all the elements within an array are the same data type, mathematical operations perform much faster with arrays relative to lists.**

**NumPy arrays have a fixed size at creation. Changing the size of an ndarray will create a new array and delete the original.**

<br/>

<sup>Source: [Documentation for NumPy](https://numpy.org/devdocs/user/whatisnumpy.html)</sup>

In [2]:
len(dir(np))
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

## **Creating NumPy Arrays**

In [3]:
array_1 = np.array([0, 1, 2, 3, 4, 5])
type(array_1)

numpy.ndarray

In [4]:
array_2 = np.arange(0, 10, dtype = float)
array_2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
two_d_array = np.arange(20).reshape((2, 10))
two_d_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [6]:
three_d_array = np.arange(30).reshape((2, 5, 3))
three_d_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [7]:
incremental_array = np.arange(0, 1.1, 0.1)
incremental_array

for i in incremental_array:
  print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9
1.0


In [8]:
complex_array = np.array([1 + 2j, 1 + 3j, 2 + 2j, 2 + 3j])

for i in complex_array:
  print(type(i))

<class 'numpy.complex128'>
<class 'numpy.complex128'>
<class 'numpy.complex128'>
<class 'numpy.complex128'>


In [9]:
num_list = [i for i in range(100)]
array_3 = np.array(num_list)
array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
zero_array = np.zeros(25)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
ones_array = np.ones((2,10))
ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## **Broadcasting**

**Broadcasting allows an operation with a scalar (real or imaginary number) and a vector (a NumPy array).**

In [12]:
array_1

array([0, 1, 2, 3, 4, 5])

In [13]:
array_1 * 2

array([ 0,  2,  4,  6,  8, 10])

In [14]:
array_1 + 2

array([2, 3, 4, 5, 6, 7])

In [15]:
array_1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [16]:
array_1 * np.complex(1 + 1j)

array([0.+0.j, 1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j, 5.+5.j])

In [17]:
three_d_array * 3

array([[[ 0,  3,  6],
        [ 9, 12, 15],
        [18, 21, 24],
        [27, 30, 33],
        [36, 39, 42]],

       [[45, 48, 51],
        [54, 57, 60],
        [63, 66, 69],
        [72, 75, 78],
        [81, 84, 87]]])

## **Speed of NumPy arrays compared to Python lists**

In [18]:
numpy_array = np.arange(0,10000)
num_list = [i for i in range(10000)]

In [19]:
#µs stands for microsecond
%timeit numpy_array = np.arange(0,10000)
%timeit num_list = [i for i in range(10000)]

The slowest run took 4.21 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.92 µs per loop
1000 loops, best of 3: 341 µs per loop


In [20]:
%timeit numpy_array * 2**.5
%timeit [i*2**.5 for i in num_list]

The slowest run took 6.80 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 11 µs per loop
1000 loops, best of 3: 614 µs per loop


In [21]:
%timeit numpy_array * numpy_array
%timeit [i*i for i in num_list]

The slowest run took 6.94 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 6.2 µs per loop
1000 loops, best of 3: 480 µs per loop


## **Memory usage of NumPy arrays compared to Python lists**

In [22]:
print("Size of Python List: %d bytes"%asizeof.asizeof(num_list))

Size of Python List: 407616 bytes


In [23]:
print("Size of NumPy Array: %d bytes"%asizeof.asizeof(numpy_array))

Size of NumPy Array: 80112 bytes


## **NumPy arrays and homogenous data types**
**Within a specific NumPy array, only one data type can be stored within the array. This contrasts with Python lists that can hold different data types within the same list.**

In [24]:
print(array_1, '\n')

for i in array_1:
  print(type(i))

[0 1 2 3 4 5] 

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [25]:
array_1 = np.append(array_1, 'num')

print(array_1, '\n')

for i in array_1:
  print(type(i))

['0' '1' '2' '3' '4' '5' 'num'] 

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [26]:
mixed_list = array_1.tolist()

mixed_list = [int(i) if i.isdecimal() else i for i in mixed_list]

for i in mixed_list:
  print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>


# **References and Additional Learning**

## **Websites**

- **[Documentation for NumPy](https://numpy.org/devdocs/contents.html)**
- **[Anaconda Individual Edition](https://www.anaconda.com/products/individual)**
- **[Monitor Memory Usage By Python Objects](https://coderzcolumn.com/tutorials/python/pympler-monitor-memory-usage-by-python-objects) from CoderzColumn**

# **Connect**
- **Feel free to connect with Adrian on [YouTube](https://www.youtube.com/channel/UCPuDxI3xb_ryUUMfkm0jsRA), [LinkedIn](https://www.linkedin.com/in/adrian-dolinay-frm-96a289106/), [Twitter](https://twitter.com/DolinayG) and [GitHub](https://github.com/ad17171717). Happy coding!**